### ISSUE TITLE
Name-List error

### ISSUE THREAD

**Issue by Meistercoach83** [vyakymenko/angular2-seed-express#1]
After npm install && npm start my browser opens correctly. The page is show, but when trying to access http://localhost:9001/api/name-list the server throws an error

NameListService.prototype.handleError(error=Response { _body=Event error, status=0, ok=false, mehr...})name-li...vice.js (Zeile 29)
CatchSubscriber.prototype.error(err=Object { type="object"})catch.js (Zeile 51)
Subscriber.prototype._error(err=Object { type="object"})Subscriber.js (Zeile 127)
Subscriber.prototype.error(err=Object { type="object"})Subscriber.js (Zeile 101)
XHRConnection/this.response</onError(err=Object { type="object"})http.umd.js (Zeile 1167)
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask(targetZone=Object { type="object"}, task=Object { type="object"}, applyThis=Object { type="object"}, applyArgs=Object { type="object"})zone.js...8994086 (Zeile 356)
NgZoneImpl/this.inner<.onInvokeTask(delegate=Object { type="object"}, current=Object { type="object"}, target=Object { type="object"}, task=Object { type="object"}, applyThis=Object { type="object"}, applyArgs=Object { type="object"})core.umd.js (Zeile 9091)
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask(targetZone=Object { type="object"}, task=Object { type="object"}, applyThis=Object { type="object"}, applyArgs=Object { type="object"})zone.js...8994086 (Zeile 355)
Zone</Zone</Zone.prototype.runTask(task=Object { type="object"}, applyThis=Object { type="object"}, applyArgs=Object { type="object"})zone.js...8994086 (Zeile 256)
ZoneTask/this.invoke()

**Comment by vyakymenko** [comment]
@Meistercoach83 , before npm start, run the server middleware
`node app.sever.dev.js`

**Comment by vyakymenko** [comment]
@Meistercoach83 , https://github.com/vyakymenko/angular2-seed-express#need-to-know

**Comment by vyakymenko** [comment]
In future middleware runner will be included to `npm start`.

**Comment by DmitryEfimenko** [comment]
Also got error that it's unable to load the list.
Made sure to start server before running `npm start`. The error is:
```
XMLHttpRequest cannot load http://localhost:9001/api/name-list. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5555' is therefore not allowed access.
```
Basically there are two servers. One is the app api and another one is there just for the purposes of serving angular app.
The quick hacky solution (that I don't think is acceptable) is to add headers on the server.
The proper way to fix this would be somehow combining the two servers.

**Comment by vyakymenko** [comment]
@DmitryEfimenko , you are right, my false in `routes`.
Fixed.

**Comment by DmitryEfimenko** [comment]
that fix broke serving list in prod because `app.get('/*', renderIndex);` now runs before `require('./routes')(app);` and therefore intercepts requests to api and serves index page instead.

**Comment by vyakymenko** [comment]
@DmitryEfimenko , I have add a temporary hotfix, that is 100% fix this issue.

**Comment by DmitryEfimenko** [comment]
thanks!
