### ISSUE TITLE
integration with mongo?

### ISSUE THREAD

**Issue by ghatul** [vyakymenko/angular2-seed-express#11]
i try to integrate project with mongo but it not working ,can u please tell  me

**Comment by vyakymenko** [comment]
@ghatul , I was thinking about it, when I will have a free time I will implement integration with mongo :)

**Comment by vyakymenko** [comment]
@ghatul , can you provide more details what are not working for you ?

**Comment by ghatul** [comment]
i use https://github.com/mgechev/angular2-seed this seed project and build my client and server in  nodejs with typescript with mongo , i try to integrate client and server as per your seed ,i suceesfully integrate client but i getting confused for integration of server ...

**Comment by vyakymenko** [comment]
@ghatul , any errors? Have you read the documentation in `README.md` ?

**Comment by ghatul** [comment]
yes , i read that

**Comment by vyakymenko** [comment]
@ghatul , can you show your `.ts` or `.js` code to connect with `MongoDB` ?

**Comment by ghatul** [comment]
`import Mongoose = require("mongoose");

class DataAccess {
    static mongooseInstance:any;
    static mongooseConnection:Mongoose.Connection;

    constructor() {
        DataAccess.connect();
    }

    static connect():Mongoose.Connection {
        if (this.mongooseInstance) return this.mongooseInstance;

        this.mongooseConnection = Mongoose.connection;
        this.mongooseConnection.once("open", () => {
            console.log("Connected to mongodb.");
        });
        /*  var host = config.get("database.host");
         var port = config.get("database.port");
         var dbName = config.get("database.name");
         console.log("Using Database: Host: %s | Port: %s | Name: %s", host, port, dbName);
         /!*connection = mongoose.connect('mongodb://' + host + ':' + port + '/' + dbName);*!/
         */
        // this.mongooseInstance = Mongoose.connect('mongodb://-:-:-:-/seed-backend');
        this.mongooseInstance = Mongoose.connect('mongodb://127.0.0.1/seed-backend');
        return this.mongooseInstance;
    }
}
DataAccess.connect();
export = DataAccess;
     `

**Comment by vyakymenko** [comment]
@ghatul , have you installed `typings install dt~mongoose --save --global` ?
You `MongoDB` is running ? What `error` do you have? Maybe you have some `debug` log ?

**Comment by Zasuk** [comment]
Hi, i'm using mongoose in my project with this seed and it's working as expected...

**Comment by Zasuk** [comment]
typings.json
` "mongoose": "registry:dt/mongoose#4.5.4+20160807120805",
`
db.conf.ts
```
'use strict';

import * as mongoose from 'mongoose';

export class DBConfig {

  static init(): void {

    const URL = 'mongodb://xxxxx/database';
    mongoose.connect(URL, (err) => {

      if (err) {

        console.log(err.message);
        console.log(err);

      } else {

        console.log('Connected to MongoDb');
      }
    });
  }
}
```

then in server/index.ts we just need to init the DBConfig
```
import { DBConfig } from './configs/db.conf';

var _clientDir = '../client';
var app = express();

export function init(port: number, mode: string) {

  app.use(bodyParser.urlencoded({extended: false}));
  app.use(bodyParser.json());
  app.use(bodyParser.text());
  app.use(compression());

  // DB Init
  DBConfig.init();
...
}
```

**Comment by ghatul** [comment]
thanks !
typings install dt~mongoose --save --global   work for me
