### ISSUE TITLE
Module Resolution in seed project?

### ISSUE THREAD

**Issue by redevill** [vyakymenko/angular2-seed-express#13]
Was trying to extend your seed to use Sequelize. Was hoping to get help on an error that appears to be related to Module resolution within the seed project. 

Have posted here: 
http://stackoverflow.com/questions/39278466/error-while-attempting-integration-of-sequelize-into-angular2-seed-express

Any help would be appreciated.
Thanks

**Comment by vyakymenko** [comment]
@redevill , `typings install dt~sequelize --save --global`

**Comment by vyakymenko** [comment]
@redevill , can we close this issue ?

**Comment by redevill** [comment]
Yes, thank youEti
