### ISSUE TITLE
Problem running 'npm run build.prod'

### ISSUE THREAD

**Issue by rylphs** [vyakymenko/angular2-seed-express#14]
When I run ''npm run build.prod", I get the following error
```

tools/tasks/seed/build.index.prod.ts (8,3): Module '"/home/07125220690/projects/tradingman/tools/config"' has no exported member 'APP_DEST'. (2305)
tools/tasks/seed/build.index.prod.ts (9,3): Module '"/home/07125220690/projects/tradingman/tools/config"' has no exported member 'APP_SRC'. (2305)
```

Looking at the file seed.config.ts indeed there is no 'APP_DEST' or 'APP_SRC' declared.

**Comment by vyakymenko** [comment]
@rylphs, thanks for funding this one , will fix very soon

**Comment by rylphs** [comment]
You're welcome, and thank you for the seed, it saved me so much time!

**Comment by vyakymenko** [comment]
@rylphs , if everything is ok now, we can close the issue.

**Comment by rylphs** [comment]
@vyakymenko, everything is ok you can close the issue. Thanks!
