### ISSUE TITLE
Current copy.client.js.prod.ts task don't allow us to share code between server and client

### ISSUE THREAD

**Issue by Zasuk** [vyakymenko/angular2-seed-express#15]
Hi, i was trying to share a model between my server and client implementation and is not possible without some changes in the current task. 

we can create a shared folder in the same level of client and server and copy it to both temp directories...what do you think?

**Comment by Zasuk** [comment]
or we can name it "core" for example

**Comment by vyakymenko** [comment]
@Zasuk , I'm not sure that this is the need because you will open the black hole in security. The server code is a server code, client code is a client code.

P.S. If you want to share model, for example, it's not an issue :)

**Comment by vyakymenko** [comment]
@Zasuk , can we close issue ?

**Comment by Zasuk** [comment]
to be honest i really need this to share models, some configs and assets...
but i think i'm the only one that needs this feature so i'll try to implement it myself
