### ISSUE TITLE
 Cannot read property 'SEED_TASKS_DIR' of undefined

### ISSUE THREAD

**Issue by ghatul** [vyakymenko/angular2-seed-express#19]
hi, i am going to migrate rc6 to 2.0 stable (all latest changes are pull into my seed)but stuck with error

/Users/Desktop/myWorkspace/tpl-web-fullstack-seed/gulpfile.ts:9
loadTasks(Config.SEED_TASKS_DIR);
^
TypeError: Cannot read property 'SEED_TASKS_DIR' of undefined
at Object.<anonymous> (/Users/techprimelab/Desktop/myWorkspace/tpl-web-fullstack-seed/gulpfile.ts:9:17)
at Module._compile (module.js:541:32)
at Module.m._compile (/Users/techprimelab/Desktop/myWorkspace/tpl-web-fullstack-seed/node_modules/ts-node/src/index.ts:299:25)
at Module._extensions..js (module.js:550:10)
at Object.require.extensions.(anonymous function) [as .ts] (/Users/techprimelab/Desktop/myWorkspace/tpl-web-fullstack-seed/node_modules/ts-node/src/index.ts:302:14)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)
at Module.require (module.js:468:17)
at require (internal/module.js:20:19)
can any one help me out

also when npm install:-
~postinstall: cannot run in wd %s %s (wd=%s) tpl-mobile-seed@2.0.1 gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver

**Comment by vyakymenko** [comment]
@ghatul , hello, have you tried clean build ?

**Comment by ghatul** [comment]
@vyakymenko
i tried for build.prod also same issue
my node version is 6.2.2
and npm v3.9.5

**Comment by ghatul** [comment]
@vyakymenko 
my node version is 6.2.2
and npm v3.9.5

i tried clean.once,build.tools,npm start

but get same error
sudo gulp clean.once
[09:45:01] Requiring external module ts-node/register

/Users/Desktop/myWorkspace/tpl-web-fullstack-seed/gulpfile.ts:9
loadTasks(Config.SEED_TASKS_DIR);
TypeError: Cannot read property 'SEED_TASKS_DIR' of undefine

**Comment by vyakymenko** [comment]
@ghatul , first one, you need to update `typings`, `$ npm install typings -g`, `typings.json` must be deleted, because it's not used by the current version. Much better after `typings` will be updated, make a clean `clone` of repository, then run `$ npm install` and then `$ npm start` an application.

**Comment by ghatul** [comment]
@vyakymenko 
typings updated , typings.json deleted .

on npm install ->get error
No compatible version found: es6-module-loader@^1.0.0

**Comment by ghatul** [comment]
@vyakymenko 
hi,
typings.json deleted from my seed.
i use some npm modules like passport ,nodemailer......etc, project functionality is working properly but give console errors like  ->Cannot find module 'nodemailer'.
                                       ->Cannot find module 'passport'.

it not getting problem for development env but production env could not be build .
before migration i was using typing.json that time not getting such issue but after remove typing.json 
getting such types of errors .How to handle that npm modules without typing.json?

**Comment by vyakymenko** [comment]
@ghatul , via `npm` only. I'm sorry, but it's not a seed issue.

**Comment by ghatul** [comment]
@vyakymenko 
thanku.
