### ISSUE TITLE
Add config for backend   

### ISSUE THREAD

**Issue by NiLeShpatil777** [vyakymenko/angular2-seed-express#22]
in config i have development.json,production.json and staging.json   ,Even though i set my ENV_NODE to production by using command 'export NODE_ENV=production' the values i am getting are all of development.
         The way i run my project is as follows
1)In first tab
export NODE_ENV=production
npm start
2)In second tab
export NODE_ENV=production
node app.server.prod.js

**Comment by vyakymenko** [comment]
@NiLeShpatil777 , for production Web Service calls, you need to build you client app in `production`. 
| Express Server

Express server run for prod build.

# run Express server (keep in touch, only after `npm run build.prod` )
# keep in mind that prod build will be builded with prod env flag
$ node app.server.prod.js
