### ISSUE TITLE
Backend debugging 

### ISSUE THREAD

**Issue by NiLeShpatil777** [vyakymenko/angular2-seed-express#23]
What steps will reproduce the problem?
1. I have two directories in my source folder one with Server which contains backend code written in node.js with typescript. I have used gulp task manager & express server to run backend code. My node version is v6.8.1
   & npm version is 3.10.7. Second directory is Client which contains front end code written in angular 2 - 2.0 version.
2. I have attached screenshot of my project structure. ( Screenshot_attachment : seed_project_1,  seed_project_2, seed_project_3)
   My Nodejs Sever directory structure is ( Screenshot_attachment : project_node_structure)
3. When I compile my project with 'npm start', transpiled files are created inside 'Dist' folder as per shown in Screenshot. ( Screenshot_attachment : project_node_compiled )
4. Screenshot with my Node.js Debug configuration. ( Screenshot_attachment :  nodejsDebuggerConfiguration )
5. Added a breakpoints in Javascript file and press Debug.
6. Here is I am getting Error for v8debug in WebStorm debugger console but not in terminal. ( Screenshot_attachment : user_controller_debug )
7. I started my front-end & when I hit login functionality it simply gives error for Server Connection. It means my server has not started yet, but in debugger it shows mongodb connection. (Screenshot_attachment : user_controller_debug)

What is the expected result ?

I want WebStorm to stop on breakpoint inside of the .ts/.js file and should be able to inspect the typescript variables as per when I debug node.js with pure javascript. ( In that earlier project, I have used separate single directory for backend code in node.js with typescript. )

What happens instead?

nothing happens, IDE doesn't stop on any typescript/Javascript file breakpoints. Though it shows green 'right' mark inside breakpoint circle (screenshot). But I am unable to Inspect the variables.

Any additional information needed is below :

I'm using Ubuntu,with webstorm IDE running grunt task.
Node.js Version : v6.8.1
Npm version : 3.10.7
Front-End : Angular 2 version 2.0
Back-End : Node.js with Typescript
![nodejsdebuggerconfiguration](https://cloud.githubusercontent.com/assets/14951809/19763772/543a3316-9c5d-11e6-85a9-bf0f1870bca8.png)
![project_node_compiled](https://cloud.githubusercontent.com/assets/14951809/19763770/54386e6e-9c5d-11e6-87ad-46840b05bded.png)
![project_node_structure](https://cloud.githubusercontent.com/assets/14951809/19763771/5439ddbc-9c5d-11e6-80b5-7deba4b52b3c.png)
![seed_project_1](https://cloud.githubusercontent.com/assets/14951809/19763773/543a634a-9c5d-11e6-8dc6-d81b852eb282.png)
![seed_project_2](https://cloud.githubusercontent.com/assets/14951809/19763774/543bb4a2-9c5d-11e6-8fdf-9679266ccde8.png)
![seed_project_3](https://cloud.githubusercontent.com/assets/14951809/19763775/543f08e6-9c5d-11e6-9609-d79cb9e3f833.png)
![settings_typescript](https://cloud.githubusercontent.com/assets/14951809/19763777/54693b2a-9c5d-11e6-9a00-77b5e7a5de76.png)
![user_controller_debug](https://cloud.githubusercontent.com/assets/14951809/19763776/54657508-9c5d-11e6-8d14-82ad793bdec3.png)

**Comment by vyakymenko** [comment]
@NiLeShpatil777 , your back-end debugging not a seed issue.

**Comment by NiLeShpatil777** [comment]
Thanks #9 worked for me .
I just configure my server folder and that's all.
http://prntscr.com/ccgg0u
