### ISSUE TITLE
serve.prod.exp is failing

### ISSUE THREAD

**Issue by zaksyed** [vyakymenko/angular2-seed-express#27]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

When I am running npm run serve.prod.exp, the script seems to be failing.

**Minimal reproduction of the problem with instructions**

Clone the latest changes and run npm run serve.prod.exp

**Please tell us about your environment:**

Mac OS, webstrom

* **Node:** `node --version` = v6.9.1

**Comment by vyakymenko** [comment]
@zaksyed , hello, thanks for this bug submitting, actually I'm working on experimental buld, sof for now it's now working.

**Comment by vyakymenko** [comment]
Issue resolved, per: https://github.com/vyakymenko/angular2-seed-express/pull/28
