### ISSUE TITLE
Progressive app support?

### ISSUE THREAD

**Issue by ghatul** [vyakymenko/angular2-seed-express#31]
hi ,
can u please guide about how to configure PWA support for this starter project.

**Comment by vyakymenko** [comment]
@ghatul , hello, I apologize, but this repo, is just an example of how to use express with angular-seed, to create the correct architecture for PWA, you need to use your own architecture depend on what do you want from your application. Example: "For installer generation for you PWA, can be used alot of frameworks, like cordova, phonegap, etc..." and more more more... I think you need to look for advanced seed: https://github.com/NathanWalker/angular-seed-advanced

**Comment by ghatul** [comment]
thanku.
