### ISSUE TITLE
 Error on fetch for angular2-indexeddb.js ?

### ISSUE THREAD

**Issue by ghatul** [vyakymenko/angular2-seed-express#32]
hi,
I stuck with configuration of indexdb on production build it get Error on fetch for angular2-indexeddb.js.It work without error on development.i cant understand how to solve this, could u please help me out.....

i tried following  project.config.ts but it not worked :-
SYSTEM_CONFIG_DEV: any = {
    defaultJSExtensions: true,
    transpiler: 'typescript', typescriptOptions: { emitDecoratorMetadata: true },
    packageConfigPaths: [
.
.
.
.
      'dragula': 'node_modules/dragula/dist/dragula.min.js',
      'angular2-indexeddb':'node_modules/angular2-indexeddb/',
      'crypto-js': 'node_modules/crypto-js/crypto-js.js',
      'app/*': '/app/*',
      // For test config
      'dist/dev/*': '/base/dist/dev/*',
      '*': 'node_modules/*'
    },
    packages: {
      'angular2-indexeddb': {
        main: 'index.ts',
        defaultExtension: 'ts'
      }
    }
  };

on gulp build.prod shows following error:-

[18:45:25] 'build.bundles.app' errored after 2.82 s
[18:45:25] Error on fetch for angular2-indexeddb.js at file:///home/node_modules/angular2-indexeddb.js
Loading dist/tmp_client/app//db-service/db.service.js
Loading dist/tmp_client/app/app.module.js
Loading dist/tmp_client/app/main.js
Error: ENOENT: no such file or directory, open '/home/node_modules/angular2-indexeddb.js'
at Error (native)
[18:45:25] 'build.prod' errored after 33 s
[18:45:25] Error in plugin 'run-sequence(build.bundles.app)'
Message:
Error on fetch for angular2-indexeddb.js at file:///home/node_modules/angular2-indexeddb.js
Loading dist/tmp_client/app/qeasily/framework/db-service/db.service.js
Loading dist/tmp_client/app/app.module.js
Loading dist/tmp_client/app/main.js
ENOENT: no such file or directory, open '/home/node_modules/angular2-indexeddb.js'
Details:
originalErr: Error: ENOENT: no such file or directory, open '/home/node_modules/angular2-indexeddb.js'
Stack:
Error on fetch for angular2-indexeddb.js at file:///home/chetan/node_modules/angular2-indexeddb.js
Loading dist/tmp_client/app/framework/db-service/db.service.js
Loading dist/tmp_client/app/app.module.js
Loading dist/tmp_client/app/main.js
Error: ENOENT: no such file or directory, open '/home/chetan/node_modules/angular2-indexeddb.js'
at Error (native)

**Comment by vyakymenko** [comment]
@ghatul , error in incorrect configuration for lib that you try to use.

Here is an example with higcharts in `project.config.ts`:
```ts
let additionalPackages: ExtendPackages[] = [
      {
        name: 'angular2-highcharts',
        // Path to the package's bundle
        path: 'node_modules/angular2-highcharts/dist/index.js'
      },{
        name: 'highcharts',
        // Path to the package's bundle
        path: 'node_modules/highcharts/highcharts.js'
      },{
        name: 'highcharts/highstock.src',
        // Path to the package's bundle
        path: 'node_modules/highcharts/highstock.js'
      },
    ];

    this.addPackagesBundles(additionalPackages);
```

Same construction will be for your `indxedDB` lib or other.

Thanks!

**Comment by ghatul** [comment]
thanku...
