### ISSUE TITLE
progressive web app with offline ?

### ISSUE THREAD

**Issue by ghatul** [vyakymenko/angular2-seed-express#33]
i am working for offline functionality with this starter app. I did all requirements which require for offline but i failed to caching all that resources in browser cache using service-worker.js. I used sw-precache for that.

changes with gulpfile.ts
1.  gulp.task('build.prod', (done: any) =>
  runSequence('check.tools',
              'clean.prod',
              //'tslint',
              //'css-lint',
              'build.assets.prod',
              'build.html_css',
              'copy.prod',
              'copy.server.js.prod',
              'build.server.prod',
              'build.js.prod',
              'build.bundles',
              'build.bundles.app',
              'minify.bundles',
              'build.index.prod',
              'copy.server.assets',
              'generate-service-worker',
              done));

2. gulp.task('generate-service-worker', (callback:any) => {
  var path = require('path');
  var swPrecache = require('sw-precache');
  var rootDir = 'dist/prod/client/';
  //var rootDir = Config.APP_CLIENT_DEST;
  util.log('---------------------generate-service-worker-----------root-directoryName---',rootDir);
  swPrecache.write(`${rootDir}/service-worker.js`, {
    staticFileGlobs: [rootDir + '/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,json}'],
    stripPrefix: rootDir
  }, callback);
});

on prod build -> after above task service-worker.js created but not worked. whats going wrong i dont know
any other seed config required ?
any suggestion?

**Comment by vyakymenko** [comment]
I apologize, but this is not seed issue.

**Comment by ghatul** [comment]
i got it, thanku!
