### ISSUE TITLE
npm start livereload to src/server

### ISSUE THREAD

**Issue by calebeaires** [vyakymenko/angular2-seed-express#37]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```
`npm start` does not watches files and uses livereload on **src/server** code. Is there some way to active it?

**Comment by vyakymenko** [comment]
@calebeaires , hello, look here:
https://github.com/vyakymenko/angular2-seed-express/issues/8

P.S. But later I will think about it.
