### ISSUE TITLE
Debug server side code

### ISSUE THREAD

**Issue by Zasuk** [vyakymenko/angular2-seed-express#9]
Hi, how can i debug the server side code in webstorm?
For the client i just need to setup a new javascript debug config and i think it will also work for server side but i think we also need the map files in dist folder....

**Comment by vyakymenko** [comment]
@Zasuk , here is server debug in `WebStorm`:
http://prntscr.com/cab71b

**Comment by vyakymenko** [comment]
@Zasuk , debug by default TypeScript impossible, we talk about it with @geekrumper in `gitter` and `JetBrains` team.
Btw we have a ticket for this one:
https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FIDEA-159932

**Comment by Zasuk** [comment]
@vyakymenko can you share your Node.js Development debug configuration? just to check if i have the same path for files...

**Comment by vyakymenko** [comment]
@Zasuk , I just configure my server folder and that's all.
Here is my screenshot:
http://prntscr.com/ccgg0u

**Comment by vyakymenko** [comment]
@Zasuk , can we close this issue ?
